filter:
    excluded_paths:
        - Resources/public
        - vendor
        - features/contexts/fixtures

tools:
    php_code_sniffer:
        config:
            standard: PSR2
    php_cpd:
        excluded_dirs:
            - Resources/public
            - vendor
            - features/contexts/fixtures
    php_cs_fixer:
        config:
            level: all
    php_hhvm: true
    php_loc:
        excluded_dirs:
            - Resources/public
            - vendor
            - features/contexts/fixtures
    php_mess_detector: true
    php_pdepend:
        excluded_dirs:
            - Resources/public
            - vendor
            - features/contexts/fixtures
    php_analyzer: true
    sensiolabs_security_checker: true