language: php

php:
  - 5.3.3
  - 5.3
  - 5.4

script: php codecept.phar run --steps --debug --html

env:
  - SYMFONY_VERSION='~2.3-dev'

before_script:
  -  sudo apt-get install -y --force-yes apache2 libapache2-mod-php5 php5-curl wkhtmltopdf
  -  wget http://pecl.php.net/get/mongo-1.2.10.tgz
  -  tar -xzf mongo-1.2.10.tgz
  -  sh -c "cd mongo-1.2.10 && phpize && ./configure && sudo make install"
  -  echo "extension=mongo.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`  - composer install
  -  DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
  -  mkdir $DIR/../log
  - java -jar $DIR/selenium-server-standalone-2.29.0.jar 1>$DIR/../log/selenium-server-standalone.log 2>&1 &
  - composer self-update
  - composer require --no-update symfony/symfony=$SYMFONY_VERSION
  - 'curl -H "Accept: text/plain" https://security.sensiolabs.org/check_lock -F lock=@composer.lock -s | grep "No known"'

branches:
  only:
    - master

notifications:
  email:
    - julien@meetserious.com