language: php

php:
  - 5.3.3
  - 5.3
  - 5.4

script: php bin/codecept run --steps --debug --html

branches:
  only:
    - master

services:
  - mongodb

notifications:
  email:
    - julien@meetserious.com