language: php

php:
  - 5.3.3
  - 5.3
  - 5.4

script: php codecept.phar run --steps --debug --html

before_script:
  - composer install

branches:
  only:
    - master

notifications:
  email:
    - julien@meetserious.com