horus_front:
    resource: "@HorusFrontBundle/Resources/config/routing.yml"
    prefix:   /

horus_site_root:
  pattern:  /
  defaults: { _controller: HorusSiteBundle:Administrateur:login }

horus_site_denied:
  pattern:  /access-denied/
  defaults: { _controller: HorusSiteBundle:Administrateur:login }


horus:
  resource: "@HorusSiteBundle/Resources/config/routing.yml"
