// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    var $addTagLink, $newLinkLi, addTagForm, addTagFormDeleteLink, collectionHolder;
    collectionHolder = $("ul.metas");
    collectionHolder.find("li").each(function() {
      return addTagFormDeleteLink($(this));
    });
    $addTagLink = $("<a href=\"#\" class=\"add_tag_link\">Add a metas</a>");
    $newLinkLi = $("<li></li>").append($addTagLink);
    collectionHolder.append($newLinkLi);
    $addTagLink.on("click", function(e) {
      e.preventDefault();
      return addTagForm(collectionHolder, $newLinkLi);
    });
    addTagFormDeleteLink = function($tagFormLi) {
      var $removeFormA;
      $removeFormA = $("<a href=\"#\">Supprimer ce tag</a>");
      $tagFormLi.append($removeFormA);
      return $removeFormA.on("click", function(e) {
        e.preventDefault();
        return $tagFormLi.remove();
      });
    };
    return addTagForm = function($collectionHolder, $newLinkLi) {
      var $newFormLi, index, newForm, prototype;
      addTagFormDeleteLink($newFormLi);
      prototype = $collectionHolder.data("prototype");
      index = $collectionHolder.data("index");
      newForm = prototype.replace(/__name__/g, index);
      $collectionHolder.data("index", index + 1);
      $newFormLi = $("<li></li>").append(newForm);
      return $newLinkLi.before($newFormLi);
    };
  });

}).call(this);
