###
### Main
###
horus_site_main:
  pattern:  /backend/
  defaults: { _controller: HorusSiteBundle:Main:index }

horus_site_root:
  pattern:  /
  defaults: { _controller: HorusSiteBundle:Administrateur:login }




###
### Products
###

horus_site_products:
  pattern:  /backend/produits
  defaults: { _controller: HorusSiteBundle:Product:products }

horus_site_remove_product:
  pattern:  /backend/produit/suppression/{id}
  defaults: { _controller: HorusSiteBundle:Product:removeproduct }

horus_site_remove_image_product:
  pattern:  /backend/produit-image/suppression/{id}
  defaults: { _controller: HorusSiteBundle:Product:removeimageproduct }

horus_site_cover_image_product:
  pattern:  /backend/produit-image/cover/{id}
  defaults: { _controller: HorusSiteBundle:Product:coverimageproduct }

horus_site_active_product:
  pattern:  /backend/produit/activation/{id}
  defaults: { _controller: HorusSiteBundle:Product:activeproduct }

horus_site_desactive_product:
  pattern:  /backend/produit/desactivation/{id}
  defaults: { _controller: HorusSiteBundle:Product:desactiveproduct }

horus_site_create_product:
  pattern:  /backend/creer-un-produit
  defaults: { _controller: HorusSiteBundle:Product:createproduct }

horus_site_edit_product:
  pattern:  /backend/editer-un-produit/{id}
  defaults: { _controller: HorusSiteBundle:Product:editproduct }

horus_site_visualize_product:
  pattern:  /backend/voir-un-produit/{id}
  defaults: { _controller: HorusSiteBundle:Product:visualizeproduct }

horus_site_edit_pictures_product:
  pattern:  /backend/photo-du-produit/{id}
  defaults: { _controller: HorusSiteBundle:Product:pictureproduct }

horus_site_commands:
  pattern:  /backend/commandes
  defaults: { _controller: HorusSiteBundle:Main:commands }




###
### Famille
###

horus_site_famille:
  pattern:  /backend/famille/{id}
  defaults: { _controller: HorusSiteBundle:Category:famille }

horus_site_familles:
  pattern:  /backend/familles
  defaults: { _controller: HorusSiteBundle:Category:familles }

horus_site_add_famille:
  pattern:  /backend/familles/ajouter
  defaults: { _controller: HorusSiteBundle:Category:createfamille }

horus_site_remove_famille:
  pattern:  /backend/familles/supprimer/{id}
  defaults: { _controller: HorusSiteBundle:Category:removefamille }

horus_site_edit_famille:
  pattern:  /backend/familles/editer/{id}
  defaults: { _controller: HorusSiteBundle:Category:editfamille }




###
### Medias
###

horus_site_medias:
  pattern:  /backend/medias
  defaults: { _controller: HorusSiteBundle:Medias:medias }




###
### Categories
###

horus_site_categories:
  pattern:  /backend/categories
  defaults: { _controller: HorusSiteBundle:Category:categories }

horus_site_add_category:
  pattern:  /backend/category/ajouter
  defaults: { _controller: HorusSiteBundle:Category:createcategory }

horus_site_edit_image_category:
  pattern:  /backend/photo-de-category/{id}
  defaults: { _controller: HorusSiteBundle:Category:picturecategory }

horus_site_category:
  pattern:  /backend/category/{id}
  defaults: { _controller: HorusSiteBundle:Category:category }

horus_site_cover_image_category:
  pattern:  /backend/category-image/cover/{id}
  defaults: { _controller: HorusSiteBundle:Category:coverimagecategory }

horus_site_remove_image_category:
  pattern:  /backend/photo-de-category/suppression/{id}
  defaults: { _controller: HorusSiteBundle:Category:removeimagecategory }

horus_site_remove_category:
  pattern:  /backend/category/supprimer/{id}
  defaults: { _controller: HorusSiteBundle:Category:removecategory }

horus_site_edit_category:
  pattern:  /backend/category/editer/{id}
  defaults: { _controller: HorusSiteBundle:Category:editcategory }

horus_site_active_category:
  pattern:  /backend/category/activation/{id}
  defaults: { _controller: HorusSiteBundle:Category:activecategory }

horus_site_desactive_category:
  pattern:  /backend/category/desactivation/{id}
  defaults: { _controller: HorusSiteBundle:Category:desactivecategory }




###
### Pages
###
horus_site_page:
  pattern:  /backend/voir-page/{id}
  defaults: { _controller: HorusSiteBundle:CMS:page }

horus_site_pages:
  pattern:  /backend/pages
  defaults: { _controller: HorusSiteBundle:CMS:pages }

horus_site_page_create:
  pattern:  /backend/page/ajouter
  defaults: { _controller: HorusSiteBundle:CMS:createpage }

horus_site_remove_page:
  pattern:  /backend/page/supprimer/{id}
  defaults: { _controller: HorusSiteBundle:CMS:removepage }

horus_site_edit_page:
  pattern:  /backend/page/editer/{id}
  defaults: { _controller: HorusSiteBundle:CMS:editpage }

horus_site_active_page:
  pattern:  /backend/page/activation/{id}
  defaults: { _controller: HorusSiteBundle:CMS:activepage }

horus_site_desactive_page:
  pattern:  /backend/page/desactivation/{id}
  defaults: { _controller: HorusSiteBundle:CMS:desactivepage }





###
### Article
###
horus_site_article:
  pattern:  /backend/voir-article/{id}
  defaults: { _controller: HorusSiteBundle:CMS:article }

horus_site_articles:
  pattern:  /backend/articles
  defaults: { _controller: HorusSiteBundle:CMS:articles }

horus_site_article_create:
  pattern:  /backend/article/ajouter
  defaults: { _controller: HorusSiteBundle:CMS:createarticle }

horus_site_remove_article:
  pattern:  /backend/article/supprimer/{id}
  defaults: { _controller: HorusSiteBundle:CMS:removearticle }

horus_site_edit_article:
  pattern:  /backend/article/editer/{id}
  defaults: { _controller: HorusSiteBundle:CMS:editarticle }

horus_site_active_article:
  pattern:  /backend/article/activation/{id}
  defaults: { _controller: HorusSiteBundle:CMS:activearticle }

horus_site_desactive_article:
  pattern:  /backend/article/desactivation/{id}
  defaults: { _controller: HorusSiteBundle:CMS:desactivearticle }





###
### Commercials
###
horus_site_commercial:
  pattern:  /backend/voir-commercial/{id}
  defaults: { _controller: HorusSiteBundle:Commercial:commercial }

horus_site_commercials:
  pattern:  /backend/commercials
  defaults: { _controller: HorusSiteBundle:Commercial:commercials }

horus_site_commercial_create:
  pattern:  /backend/commercial/ajouter
  defaults: { _controller: HorusSiteBundle:Commercial:createcommercial }

horus_site_remove_commercial:
  pattern:  /backend/commercial/supprimer/{id}
  defaults: { _controller: HorusSiteBundle:Commercial:removecommercial }

horus_site_edit_commercial:
  pattern:  /backend/commercial/editer/{id}
  defaults: { _controller: HorusSiteBundle:Commercial:editcommercial }

horus_site_active_commercial:
  pattern:  /backend/commercial/activation/{id}
  defaults: { _controller: HorusSiteBundle:Commercial:activecommercial }

horus_site_desactive_commercial:
  pattern:  /backend/commercial/desactivation/{id}
  defaults: { _controller: HorusSiteBundle:Commercial:desactivecommercial }






###
### Tags
###
horus_site_tag:
  pattern:  /backend/voir-tag/{id}
  defaults: { _controller: HorusSiteBundle:CMS:tag }

horus_site_tags:
  pattern:  /backend/tags
  defaults: { _controller: HorusSiteBundle:CMS:tags }

horus_site_tag_create:
  pattern:  /backend/tag/ajouter
  defaults: { _controller: HorusSiteBundle:CMS:createtag }

horus_site_remove_tag:
  pattern:  /backend/tag/supprimer/{id}
  defaults: { _controller: HorusSiteBundle:CMS:removetag }

horus_site_edit_tag:
  pattern:  /backend/tag/editer/{id}
  defaults: { _controller: HorusSiteBundle:CMS:edittag }



###
### Statics
###
horus_about:
  pattern:  /about
  defaults: { _controller: HorusSiteBundle:Main:about }

horus_contact:
  pattern:  /contact
  defaults: { _controller: HorusSiteBundle:Main:contact }

horus_search_avanced:
    pattern:  /recherche/
    defaults: { _controller: HorusSiteBundle:Main:search }

login:
  pattern:  /login
  defaults: { _controller: HorusSiteBundle:Administrateur:login }

login_check:
  pattern:   /backend/login_check

logout:
  pattern:   /backend/logout
