###
### Main
###

horus_site_root:
  pattern:  /
  defaults: { _controller: HorusSiteBundle:Administrateur:login }

horus_site_main:
  pattern:  /backend/
  defaults: { _controller: HorusSiteBundle:Main:index }




###
### Products
###

horus_site_products:
  pattern:  /backend/produits
  defaults: { _controller: HorusSiteBundle:Product:products }

horus_site_create_product:
  pattern:  /backend/produits/creer
  defaults: { _controller: HorusSiteBundle:Product:createproduct }

horus_site_edit_product:
  pattern:  /backend/produits/editer/{id}
  defaults: { _controller: HorusSiteBundle:Product:editproduct }

horus_site_product:
  pattern:  /backend/produit/{id}
  defaults: { _controller: HorusSiteBundle:Product:seeproduct }

horus_site_product_add_quantity:
  pattern:  /backend/produit-add-quantity/{id}
  defaults: { _controller: HorusSiteBundle:Product:addquantityproduct }

horus_site_product_remove_quantity:
  pattern:  /backend/produit-remove-quantity/{id}
  defaults: { _controller: HorusSiteBundle:Product:removequantityproduct }

horus_site_remove_product:
  pattern:  /backend/produits/suppression/{id}
  defaults: { _controller: HorusSiteBundle:Product:removeproduct }

horus_site_remove_image_product:
  pattern:  /backend/produits/image/suppression/{id}
  defaults: { _controller: HorusSiteBundle:Product:removeimageproduct }

horus_site_cover_image_product:
  pattern:  /backend/produits/image/cover/{id}
  defaults: { _controller: HorusSiteBundle:Product:coverimageproduct }

horus_site_active_product:
  pattern:  /backend/produits/activation/{id}
  defaults: { _controller: HorusSiteBundle:Product:activeproduct }

horus_site_desactive_product:
  pattern:  /backend/produits/desactivation/{id}
  defaults: { _controller: HorusSiteBundle:Product:desactiveproduct }

horus_site_edit_pictures_product:
  pattern:  /backend/produits/photo/{id}
  defaults: { _controller: HorusSiteBundle:Product:pictureproduct }



###
### Famille
###

horus_site_familles:
  pattern:  /backend/familles
  defaults: { _controller: HorusSiteBundle:Category:familles }

horus_site_famille:
  pattern:  /backend/famille/{id}
  defaults: { _controller: HorusSiteBundle:Category:famille }

horus_site_add_famille:
  pattern:  /backend/familles/ajouter
  defaults: { _controller: HorusSiteBundle:Category:createfamille }

horus_site_remove_famille:
  pattern:  /backend/familles/supprimer/{id}
  defaults: { _controller: HorusSiteBundle:Category:removefamille }

horus_site_edit_famille:
  pattern:  /backend/familles/editer/{id}
  defaults: { _controller: HorusSiteBundle:Category:editfamille }



###
### Medias
###

horus_site_medias:
  pattern:  /backend/medias
  defaults: { _controller: HorusSiteBundle:Medias:medias }


horus_site_media_remove:
  pattern:  /backend/medias/remove/{id}
  defaults: { _controller: HorusSiteBundle:Medias:removemedias }





###
### Commentaire
###

horus_site_commentaires:
  pattern:  /backend/commentaires
  defaults: { _controller: HorusSiteBundle:Clients:commentaires }




###
### Clients
###

horus_site_clients:
  pattern:  /backend/clients
  defaults: { _controller: HorusSiteBundle:Clients:clients }




###
### Transports
###

horus_site_transports:
  pattern:  /backend/transports
  defaults: { _controller: HorusSiteBundle:Transports:transports }

horus_site_create_transport:
  pattern:  /backend/transports/creer
  defaults: { _controller: HorusSiteBundle:Transports:createtransport }

horus_site_edit_transport:
  pattern:  /backend/transports/editer/{id}
  defaults: { _controller: HorusSiteBundle:Transports:edittransport }

horus_site_remove_transport:
  pattern:  /backend/transports/suppression/{id}
  defaults: { _controller: HorusSiteBundle:Transports:removetransport }

horus_site_active_transport:
  pattern:  /backend/transports/activation/{id}
  defaults: { _controller: HorusSiteBundle:Transports:activetransport }

horus_site_desactive_transport:
  pattern:  /backend/transports/desactivation/{id}
  defaults: { _controller: HorusSiteBundle:Transports:desactivetransport }



###
### Paniers
###

horus_site_paniers:
  pattern:  /backend/paniers
  defaults: { _controller: HorusSiteBundle:Clients:paniers }




###
### Charts
###

horus_site_charts:
  pattern:  /backend/chart
  defaults: { _controller: HorusSiteBundle:Chart:main }





###
### Categories
###

horus_site_categories:
  pattern:  /backend/categories
  defaults: { _controller: HorusSiteBundle:Category:categories }

horus_site_add_category:
  pattern:  /backend/categories/ajouter
  defaults: { _controller: HorusSiteBundle:Category:createcategory }

horus_site_edit_image_category:
  pattern:  /backend/categories/image/voir/{id}
  defaults: { _controller: HorusSiteBundle:Category:picturecategory }

horus_site_category:
  pattern:  /backend/categorie/{id}
  defaults: { _controller: HorusSiteBundle:Category:category }

horus_site_cover_image_category:
  pattern:  /backend/categories/image/cover/{id}
  defaults: { _controller: HorusSiteBundle:Category:coverimagecategory }

horus_site_remove_image_category:
  pattern:  /backend/categories/image/suppression/{id}
  defaults: { _controller: HorusSiteBundle:Category:removeimagecategory }

horus_site_remove_category:
  pattern:  /backend/categories/supprimer/{id}
  defaults: { _controller: HorusSiteBundle:Category:removecategory }

horus_site_edit_category:
  pattern:  /backend/categories/editer/{id}
  defaults: { _controller: HorusSiteBundle:Category:editcategory }

horus_site_active_category:
  pattern:  /backend/categories/activation/{id}
  defaults: { _controller: HorusSiteBundle:Category:activecategory }

horus_site_desactive_category:
  pattern:  /backend/categories/desactivation/{id}
  defaults: { _controller: HorusSiteBundle:Category:desactivecategory }




###
### Pages
###
horus_site_page:
  pattern:  /backend/page/{id}
  defaults: { _controller: HorusSiteBundle:CMS:page }

horus_site_pages:
  pattern:  /backend/pages
  defaults: { _controller: HorusSiteBundle:CMS:pages }

horus_site_page_create:
  pattern:  /backend/pages/ajouter
  defaults: { _controller: HorusSiteBundle:CMS:createpage }

horus_site_remove_page:
  pattern:  /backend/pages/supprimer/{id}
  defaults: { _controller: HorusSiteBundle:CMS:removepage }

horus_site_edit_page:
  pattern:  /backend/pages/editer/{id}
  defaults: { _controller: HorusSiteBundle:CMS:editpage }

horus_site_active_page:
  pattern:  /backend/pages/activation/{id}
  defaults: { _controller: HorusSiteBundle:CMS:activepage }

horus_site_desactive_page:
  pattern:  /backend/pages/desactivation/{id}
  defaults: { _controller: HorusSiteBundle:CMS:desactivepage }





###
### Orders
###

horus_site_commandes:
  pattern:  /backend/commandes
  defaults: { _controller: HorusSiteBundle:Clients:commandes }







###
### Article
###
horus_site_article:
  pattern:  /backend/article/{id}
  defaults: { _controller: HorusSiteBundle:CMS:article }

horus_site_articles:
  pattern:  /backend/articles
  defaults: { _controller: HorusSiteBundle:CMS:articles }

horus_site_article_create:
  pattern:  /backend/articles/ajouter
  defaults: { _controller: HorusSiteBundle:CMS:createarticle }

horus_site_remove_article:
  pattern:  /backend/articles/supprimer/{id}
  defaults: { _controller: HorusSiteBundle:CMS:removearticle }

horus_site_edit_article:
  pattern:  /backend/articles/editer/{id}
  defaults: { _controller: HorusSiteBundle:CMS:editarticle }

horus_site_active_article:
  pattern:  /backend/articles/activation/{id}
  defaults: { _controller: HorusSiteBundle:CMS:activearticle }

horus_site_desactive_article:
  pattern:  /backend/articles/desactivation/{id}
  defaults: { _controller: HorusSiteBundle:CMS:desactivearticle }





###
### Commercials
###
horus_site_commercial:
  pattern:  /backend/commercial/{id}
  defaults: { _controller: HorusSiteBundle:Commercial:commercial }

horus_site_commercials:
  pattern:  /backend/commercials
  defaults: { _controller: HorusSiteBundle:Commercial:commercials }

horus_site_commercial_create:
  pattern:  /backend/commercials/ajouter
  defaults: { _controller: HorusSiteBundle:Commercial:createcommercial }

horus_site_remove_commercial:
  pattern:  /backend/commercials/supprimer/{id}
  defaults: { _controller: HorusSiteBundle:Commercial:removecommercial }

horus_site_edit_commercial:
  pattern:  /backend/commercials/editer/{id}
  defaults: { _controller: HorusSiteBundle:Commercial:editcommercial }

horus_site_active_commercial:
  pattern:  /backend/commercials/activation/{id}
  defaults: { _controller: HorusSiteBundle:Commercial:activecommercial }

horus_site_desactive_commercial:
  pattern:  /backend/commercials/desactivation/{id}
  defaults: { _controller: HorusSiteBundle:Commercial:desactivecommercial }






###
### Tags
###
horus_site_tag:
  pattern:  /backend/tag/{id}
  defaults: { _controller: HorusSiteBundle:CMS:tag }

horus_site_tags:
  pattern:  /backend/tags
  defaults: { _controller: HorusSiteBundle:CMS:tags }

horus_site_tag_create:
  pattern:  /backend/tags/ajouter
  defaults: { _controller: HorusSiteBundle:CMS:createtag }

horus_site_remove_tag:
  pattern:  /backend/tags/supprimer/{id}
  defaults: { _controller: HorusSiteBundle:CMS:removetag }

horus_site_edit_tag:
  pattern:  /backend/tags/editer/{id}
  defaults: { _controller: HorusSiteBundle:CMS:edittag }




###
### Factures
###
horus_site_factures:
  pattern:  /backend/factures/
  defaults: { _controller: HorusSiteBundle:Clients:factures }




###
### Statics
###
horus_about:
  pattern:  /about
  defaults: { _controller: HorusSiteBundle:Main:about }

horus_contact:
  pattern:  /contact
  defaults: { _controller: HorusSiteBundle:Main:contact }

horus_search_avanced:
    pattern:  /recherche/
    defaults: { _controller: HorusSiteBundle:Main:search }

login:
  pattern:  /login
  defaults: { _controller: HorusSiteBundle:Administrateur:login }

login_check:
  pattern:   /backend/login_check

logout:
  pattern:   /backend/logout
